name: Roost Web Deployment

env:
  AZURE_WEBAPP_NAME: ww-roost-web    
  BACKEND_PUBLISH_PATH: './publish'
  FRONTEND_PUBLISH_PATH: './publish/wwwroot' 
  DOTNET_VERSION: '8'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies for backend
        run: dotnet restore ./Roost.Web.Server/Roost.Web.Server.csproj

      - name: Build backend
        run: dotnet build --configuration Release --no-restore ./Roost.Web.Server/Roost.Web.Server.csproj

      - name: dotnet publish
        run: dotnet publish ./Roost.Web.Server/Roost.Web.Server.csproj -c Release --no-build -o ${{env.BACKEND_PUBLISH_PATH}}
              
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "${{ env.BACKEND_PUBLISH_PATH }}"
